(() => {
'use strict';
const IMG_W=1200,IMG_H=2133,UNIT=.01,WORLD_W=IMG_W*UNIT,WORLD_H=IMG_H*UNIT;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const V={add:(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]],sub:(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]],mul:(a,s)=>[a[0]*s,a[1]*s,a[2]*s],dot:(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2],cross:(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],len:a=>Math.hypot(a[0],a[1],a[2]),norm:a=>{const l=Math.hypot(a[0],a[1],a[2])||1;return[a[0]/l,a[1]/l,a[2]/l]}};
function perspective(fovy,aspect,near,far){const f=1/Math.tan(fovy/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,(2*far*near)*nf,0])}
function lookAt(eye,center,up){const z=V.norm(V.sub(eye,center)),x=V.norm(V.cross(up,z)),y=V.cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-V.dot(x,eye),-V.dot(y,eye),-V.dot(z,eye),1])}
function area(p){let a=0;for(let i=0;i<p.length;i++){const q=p[(i+1)%p.length];a+=p[i][0]*q[1]-q[0]*p[i][1]}return a/2}
const c2=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
function inTri(p,a,b,c){const x=c2(a,b,p),y=c2(b,c,p),z=c2(c,a,p),neg=x<0||y<0||z<0,pos=x>0||y>0||z>0;return!(neg&&pos)}
function triangulate(points){if(points.length<3)return[];let v=points.map(p=>[+p[0],+p[1]]);if(area(v)<0)v.reverse();const out=[];let guard=0;while(v.length>3&&guard++<100){let found=false;for(let i=0;i<v.length;i++){const a=v[(i-1+v.length)%v.length],b=v[i],c=v[(i+1)%v.length];if(c2(a,b,c)<=1e-8)continue;let has=false;for(let j=0;j<v.length;j++){if(j===i||j===(i-1+v.length)%v.length||j===(i+1)%v.length)continue;if(inTri(v[j],a,b,c)){has=true;break}}if(has)continue;out.push([a,b,c]);v.splice(i,1);found=true;break}if(!found)break}if(v.length===3)out.push([v[0],v[1],v[2]]);if(!out.length)for(let i=1;i<points.length-1;i++)out.push([points[0],points[i],points[i+1]]);return out}
function inside(x,y,p){let yes=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const a=p[i],b=p[j];if(((a[1]>y)!=(b[1]>y))&&(x<(b[0]-a[0])*(y-a[1])/((b[1]-a[1])||1e-9)+a[0]))yes=!yes}return yes}
function shader(gl,t,s){const o=gl.createShader(t);gl.shaderSource(o,s);gl.compileShader(o);if(!gl.getShaderParameter(o,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(o));return o}
function prog(gl,v,f){const p=gl.createProgram();gl.attachShader(p,shader(gl,gl.VERTEX_SHADER,v));gl.attachShader(p,shader(gl,gl.FRAGMENT_SHADER,f));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p}
function buf(gl,a){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(a),gl.STATIC_DRAW);return b}
class Tiyansh3D{
 constructor(host,opt={}){this.host=host;this.plots=opt.plots||[];this.onSelect=opt.onSelect||(()=>{});this.onCamera=opt.onCamera||(()=>{});this.byId=new Map(this.plots.map(p=>[p.id,p]));this.active=false;this.showAll=false;this.statusFilter=null;this.selected=null;this.sel=null;this.flat=new Map();this.baseDistance=29;this.cam={yaw:-.38,polar:.76,distance:29,target:[0,0,0]};this.def=JSON.parse(JSON.stringify(this.cam));this.fov=44*Math.PI/180;this.ptr=new Map();this.g=null;this.dpr=Math.min(devicePixelRatio||1,1.7);this.raf=0;host.innerHTML='<canvas class="three-canvas" aria-label="3D masterplan"></canvas><div class="three-loading">Preparing 3D view…</div>';this.canvas=host.querySelector('canvas');this.loading=host.querySelector('.three-loading');this.gl=this.canvas.getContext('webgl',{antialias:true,alpha:false,preserveDrawingBuffer:true});if(!this.gl)throw Error('WebGL unavailable');this.init();this.bind();this.texture()}
 init(){const gl=this.gl,vs='attribute vec3 aPos;uniform mat4 uProj,uView;void main(){gl_Position=uProj*uView*vec4(aPos,1.0);}';this.cp=prog(gl,vs,'precision mediump float;uniform vec4 uColor;void main(){gl_FragColor=uColor;}');this.cl={p:gl.getAttribLocation(this.cp,'aPos'),P:gl.getUniformLocation(this.cp,'uProj'),V:gl.getUniformLocation(this.cp,'uView'),c:gl.getUniformLocation(this.cp,'uColor')};this.tp=prog(gl,'attribute vec3 aPos;attribute vec2 aUV;uniform mat4 uProj,uView;varying vec2 uv;void main(){uv=aUV;gl_Position=uProj*uView*vec4(aPos,1.0);}','precision mediump float;uniform sampler2D uTex;varying vec2 uv;void main(){vec4 c=texture2D(uTex,uv);c.rgb=pow(c.rgb,vec3(.97));gl_FragColor=c;}');this.tl={p:gl.getAttribLocation(this.tp,'aPos'),u:gl.getAttribLocation(this.tp,'aUV'),P:gl.getUniformLocation(this.tp,'uProj'),V:gl.getUniformLocation(this.tp,'uView'),t:gl.getUniformLocation(this.tp,'uTex')};const w=WORLD_W/2,h=WORLD_H/2;this.gbuf=buf(gl,[-w,0,-h,0,1,w,0,-h,1,1,w,0,h,1,0,-w,0,-h,0,1,w,0,h,1,0,-w,0,h,0,0]);const c=[[-w,-h],[w,-h],[w,h],[-w,h]],s=[];for(let i=0;i<4;i++){const a=c[i],b=c[(i+1)%4];s.push(a[0],-.18,a[1],b[0],-.18,b[1],b[0],0,b[1],a[0],-.18,a[1],b[0],0,b[1],a[0],0,a[1])}this.side=buf(gl,s);this.sideN=s.length/3;gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.clearColor(.008,.015,.032,1)}
 texture(){const gl=this.gl,i=new Image();i.onload=()=>{this.tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.tex);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,i);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);this.loading.style.opacity='0';setTimeout(()=>this.loading.style.display='none',200);this.request()};i.src='masterplan.jpg'}
 bind(){const c=this.canvas;c.addEventListener('contextmenu',e=>e.preventDefault());c.addEventListener('pointerdown',e=>this.down(e));c.addEventListener('pointermove',e=>this.move(e));c.addEventListener('pointerup',e=>this.up(e));c.addEventListener('pointercancel',e=>this.up(e));c.addEventListener('wheel',e=>{e.preventDefault();this.cam.distance=clamp(this.cam.distance*(e.deltaY<0?.9:1.1),7,46);this.changed()},{passive:false})}
 activate(){this.active=true;this.resize();this.request()} deactivate(){this.active=false}
 resize(skipRender=false){const r=this.host.getBoundingClientRect(),w=Math.max(1,Math.round(r.width*this.dpr)),h=Math.max(1,Math.round(r.height*this.dpr));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;this.canvas.style.width=r.width+'px';this.canvas.style.height=r.height+'px'}if(!skipRender)this.request()}
 eye(){const c=this.cam,s=Math.sin(c.polar);return[c.target[0]+c.distance*s*Math.sin(c.yaw),c.target[1]+c.distance*Math.cos(c.polar),c.target[2]+c.distance*s*Math.cos(c.yaw)]}
 changed(){this.onCamera({yaw:this.cam.yaw,zoomPercent:clamp(Math.round(34*this.baseDistance/this.cam.distance),18,100)});this.request()}
 reset(){this.cam=JSON.parse(JSON.stringify(this.def));this.changed()} zoom(f){this.cam.distance=clamp(this.cam.distance*f,7,46);this.changed()}
 down(e){this.canvas.setPointerCapture?.(e.pointerId);this.ptr.set(e.pointerId,{x:e.clientX,y:e.clientY});if(this.ptr.size===1)this.g={t:'orbit',id:e.pointerId,x:e.clientX,y:e.clientY,yaw:this.cam.yaw,pol:this.cam.polar,m:false};else if(this.ptr.size===2){const[a,b]=[...this.ptr.values()];this.g={t:'pinch',d:Math.hypot(a.x-b.x,a.y-b.y),mid:[(a.x+b.x)/2,(a.y+b.y)/2],dist:this.cam.distance,target:[...this.cam.target],m:true}}}
 move(e){if(!this.ptr.has(e.pointerId))return;this.ptr.set(e.pointerId,{x:e.clientX,y:e.clientY});if(this.ptr.size===2){const[a,b]=[...this.ptr.values()],d=Math.max(10,Math.hypot(a.x-b.x,a.y-b.y)),m=[(a.x+b.x)/2,(a.y+b.y)/2];if(!this.g||this.g.t!=='pinch')this.g={t:'pinch',d,mid:m,dist:this.cam.distance,target:[...this.cam.target],m:true};this.cam.distance=clamp(this.g.dist*this.g.d/d,7,46);const dx=m[0]-this.g.mid[0],dy=m[1]-this.g.mid[1],k=this.cam.distance*.003,right=[Math.cos(this.cam.yaw),0,-Math.sin(this.cam.yaw)],fw=[-Math.sin(this.cam.yaw),0,-Math.cos(this.cam.yaw)];this.cam.target[0]=clamp(this.g.target[0]-dx*k*right[0]+dy*k*fw[0],-WORLD_W*.7,WORLD_W*.7);this.cam.target[2]=clamp(this.g.target[2]-dx*k*right[2]+dy*k*fw[2],-WORLD_H*.7,WORLD_H*.7);this.changed();return}if(this.ptr.size===1&&this.g?.t==='orbit'&&this.g.id===e.pointerId){const dx=e.clientX-this.g.x,dy=e.clientY-this.g.y;if(Math.hypot(dx,dy)>6)this.g.m=true;this.cam.yaw=this.g.yaw-dx*.008;this.cam.polar=clamp(this.g.pol+dy*.006,.18,1.46);this.changed()}}
 up(e){const pick=this.g?.t==='orbit'&&this.g.id===e.pointerId&&!this.g.m&&this.ptr.size===1;this.ptr.delete(e.pointerId);if(pick)this.pick(e.clientX,e.clientY);if(this.ptr.size===1){const[id,p]=[...this.ptr.entries()][0];this.g={t:'orbit',id,x:p.x,y:p.y,yaw:this.cam.yaw,pol:this.cam.polar,m:true}}else if(!this.ptr.size)this.g=null}
 pick(x,y){const r=this.canvas.getBoundingClientRect(),nx=2*(x-r.left)/r.width-1,ny=1-2*(y-r.top)/r.height,eye=this.eye(),fw=V.norm(V.sub(this.cam.target,eye)),right=V.norm(V.cross(fw,[0,1,0])),up=V.norm(V.cross(right,fw)),t=Math.tan(this.fov/2),dir=V.norm(V.add(fw,V.add(V.mul(right,nx*(r.width/r.height)*t),V.mul(up,ny*t))));if(Math.abs(dir[1])<1e-6)return;const k=-eye[1]/dir[1];if(k<=0)return;const hit=V.add(eye,V.mul(dir,k)),px=hit[0]/UNIT+IMG_W/2,py=hit[2]/UNIT+IMG_H/2,p=this.plots.find(p=>inside(px,py,p.points));if(p)this.select(p.id,false,true)}
 wp(p,y=.02){return[(p[0]-IMG_W/2)*UNIT,y,(p[1]-IMG_H/2)*UNIT]}
 flatGeom(p){const a=[];for(const t of triangulate(p.points))for(const x of t)a.push(...this.wp(x,.025));return{b:buf(this.gl,a),n:a.length/3}}
 build(p){const gl=this.gl,H=0.55,top=[],sh=[],side=[],loop=[],vert=[];for(const t of triangulate(p.points))for(const x of t){top.push(...this.wp(x,H));const w=this.wp(x,.011);sh.push(w[0]+.12,w[1],w[2]+.1)}for(let i=0;i<p.points.length;i++){const a=this.wp(p.points[i],.026),b=this.wp(p.points[(i+1)%p.points.length],.026),at=[a[0],H,a[2]],bt=[b[0],H,b[2]];side.push(...a,...b,...bt,...a,...bt,...at);loop.push(...at);vert.push(...a,...at)}return{top:{b:buf(gl,top),n:top.length/3},sh:{b:buf(gl,sh),n:sh.length/3},side:{b:buf(gl,side),n:side.length/3},loop:{b:buf(gl,loop),n:loop.length/3},vert:{b:buf(gl,vert),n:vert.length/3}}}
 clearSel(){if(this.sel){for(const k in this.sel)this.gl.deleteBuffer(this.sel[k].b)}this.sel=null}
 select(id,focus=false,notify=false){const p=this.byId.get(id);if(!p)return;this.clearSel();this.selected=p;this.sel=this.build(p);if(focus)this.focus(p);else this.request();if(notify)this.onSelect(p)}
 clear(){this.clearSel();this.selected=null;this.request()} setShowAll(v){this.showAll=!!v;this.request()} setStatusFilter(v){this.statusFilter=v||null;this.request()}
 focus(p){this.cam.target=[(p.center[0]-IMG_W/2)*UNIT,0,(p.center[1]-IMG_H/2)*UNIT];this.cam.distance=14;this.cam.polar=.98;this.changed()}
 color(b,n,c,mode){const gl=this.gl,l=this.cl;gl.useProgram(this.cp);gl.uniformMatrix4fv(l.P,false,this.P);gl.uniformMatrix4fv(l.V,false,this.V);gl.uniform4fv(l.c,c);gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.enableVertexAttribArray(l.p);gl.vertexAttribPointer(l.p,3,gl.FLOAT,false,0,0);gl.drawArrays(mode||gl.TRIANGLES,0,n)}
 render(){this.raf=0;if(!this.active)return;this.resize(true);const gl=this.gl;this.P=perspective(this.fov,this.canvas.width/this.canvas.height,.1,100);this.V=lookAt(this.eye(),this.cam.target,[0,1,0]);gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);this.color(this.side,this.sideN,new Float32Array([.04,.055,.07,1]));if(this.tex){gl.useProgram(this.tp);gl.uniformMatrix4fv(this.tl.P,false,this.P);gl.uniformMatrix4fv(this.tl.V,false,this.V);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.tex);gl.uniform1i(this.tl.t,0);gl.bindBuffer(gl.ARRAY_BUFFER,this.gbuf);gl.enableVertexAttribArray(this.tl.p);gl.vertexAttribPointer(this.tl.p,3,gl.FLOAT,false,20,0);gl.enableVertexAttribArray(this.tl.u);gl.vertexAttribPointer(this.tl.u,2,gl.FLOAT,false,20,12);gl.drawArrays(gl.TRIANGLES,0,6)}if(this.showAll||this.statusFilter){gl.depthMask(false);for(const p of this.plots){const st=String(p.status||'available').toLowerCase()==='enquire'?'available':String(p.status||'available').toLowerCase();if(this.statusFilter&&st!==this.statusFilter)continue;let g=this.flat.get(p.id);if(!g){g=this.flatGeom(p);this.flat.set(p.id,g)}const c=st==='sold'?[.94,.08,.15,.20]:st==='booked'?[.98,.68,.04,.20]:[.02,.82,.37,.16];this.color(g.b,g.n,new Float32Array(c))}gl.depthMask(true)}if(this.sel){gl.depthMask(false);this.color(this.sel.sh.b,this.sel.sh.n,new Float32Array([0,0,0,.24]));gl.depthMask(true);this.color(this.sel.side.b,this.sel.side.n,new Float32Array([.01,.76,.31,.67]));this.color(this.sel.top.b,this.sel.top.n,new Float32Array([.03,.9,.42,.48]));gl.depthMask(false);this.color(this.sel.loop.b,this.sel.loop.n,new Float32Array([.17,1,.55,.98]),gl.LINE_LOOP);this.color(this.sel.vert.b,this.sel.vert.n,new Float32Array([.1,.96,.45,.88]),gl.LINES);gl.depthMask(true)}}
 request(){if(this.active&&!this.raf)this.raf=requestAnimationFrame(()=>this.render())}
}
window.Tiyansh3D=Tiyansh3D;
})();