"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import { Building2,ImagePlus,LayoutDashboard,Map as MapIcon,Phone,Save,Settings,Trash2,Upload,ExternalLink,Users } from "lucide-react";
import ClientAdminManager from "./client-admin-manager";
import plotInventory from "../public/plots.json";
type Plot={id:string;sqft:number;sqm:number;sqyd:number;dimensions:string;road:string;status:string;notes?:string;featured?:boolean;polygon?:string};
type Gallery={id:string;filename:string;caption:string};
const tiyanshDefaults={projectName:"Tiyansh — The Prime Square",brandName:"TIYANSH",brandShort:"TPS",template:"plots",accentColor:"#f0b323",location:"Raigarh, Chhattisgarh",address:"Behind NH-49, Kena Pali Road, Ambihouna, Raigarh (C.G.)",phone1:"+91 90099-95582",phone2:"+91 883 998 1584",whatsapp:"919009995582",mapUrl:"https://maps.google.com",brochureUrl:""};
const genericDefaults={projectName:"New Project",brandName:"PROJECT",brandShort:"PRJ",template:"plots",accentColor:"#f0b323",location:"",address:"",phone1:"",phone2:"",whatsapp:"",mapUrl:"",brochureUrl:""};
type ProjectSettings=typeof tiyanshDefaults&{logoName?:string;logoVersion?:string};
const COMPLETED_PROJECT_ID="tiyansh-prime-square";
const baseNavItems=[["overview",LayoutDashboard,"Overview"],["plots",MapIcon,"Plots"],["gallery",ImagePlus,"Gallery"],["settings",Settings,"Settings"]] as const;
const settingLabels:Record<keyof typeof tiyanshDefaults,string>={projectName:"Project name",brandName:"Brand name",brandShort:"Short logo text",template:"Website template",accentColor:"Brand accent colour",location:"Location",address:"Full address",phone1:"Primary phone",phone2:"Secondary phone",whatsapp:"WhatsApp number",mapUrl:"Google Maps link",brochureUrl:"Brochure link"};
export default function AdminDashboard({user,signOut,projectId}:{user:{name:string;email:string;role:"super_admin"|"client_admin"};signOut:string;projectId:string}){
 const isTiyansh=projectId===COMPLETED_PROJECT_ID,initialDefaults=isTiyansh?tiyanshDefaults:genericDefaults;
 const basePlots=useMemo(()=>(isTiyansh?(plotInventory as Plot[]):[]).map(p=>({...p,status:p.status==="enquire"?"available":p.status})),[isTiyansh]);
 const [tab,setTab]=useState("overview"),[plots,setPlots]=useState<Plot[]>(basePlots),[selected,setSelected]=useState<Plot|null>(basePlots[0]||null),[gallery,setGallery]=useState<Gallery[]>([]),[settings,setSettings]=useState<ProjectSettings>(initialDefaults),[busy,setBusy]=useState(false),[statusBusy,setStatusBusy]=useState(""),[deleteBusy,setDeleteBusy]=useState(""),[toast,setToast]=useState(""),[uploadFiles,setUploadFiles]=useState<File[]>([]),[uploadPreviews,setUploadPreviews]=useState<string[]>([]),[uploadProgress,setUploadProgress]=useState<number|null>(null),[uploadCurrent,setUploadCurrent]=useState(0);
 const toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null),previewRef=useRef<string[]>([]);
 useEffect(()=>{const controller=new AbortController();async function load(){try{const savedResponse=await fetch("/api/data",{cache:"no-store",signal:controller.signal});if(!savedResponse.ok)throw new Error();const data=await savedResponse.json() as {projectName?:string;publicHost?:string|null;plots?:Plot[];gallery?:Gallery[];settings?:Partial<ProjectSettings>};const saved=new Map((data.plots||[]).map((p:Plot)=>[p.id,p])),bundledIds=new Set(basePlots.map(p=>p.id)),merged=[...basePlots.map(p=>saved.get(p.id)||p),...(data.plots||[]).filter((p:Plot)=>!bundledIds.has(p.id))];setPlots(merged);setGallery(data.gallery||[]);setSettings({...initialDefaults,projectName:data.projectName||initialDefaults.projectName,...data.settings});setSelected(current=>current?merged.find(p=>p.id===current.id)||merged[0]||null:merged[0]||null)}catch{/* Bundled plot inventory remains usable if saved data is temporarily unavailable. */}}load();return()=>controller.abort()},[basePlots,initialDefaults]);
 useEffect(()=>{previewRef.current=uploadPreviews},[uploadPreviews]);
 useEffect(()=>()=>{previewRef.current.forEach(URL.revokeObjectURL);if(toastTimer.current)clearTimeout(toastTimer.current)},[]);
 const counts=useMemo(()=>plots.reduce((a,p)=>{const s=p.status==="enquire"?"available":p.status;a[s]=(a[s]||0)+1;return a},{available:0,booked:0,sold:0} as Record<string,number>),[plots]);
 function show(v:string){setToast(v);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(""),2600)}
 async function changeStatus(plot:Plot,status:string){const previous=plot.status,updated={...plot,status};setStatusBusy(plot.id);setPlots(x=>x.map(p=>p.id===plot.id?updated:p));if(selected?.id===plot.id)setSelected(updated);try{const r=await fetch("/api/data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"plot",plot:updated})});if(!r.ok)throw new Error("Save failed");show(`${plot.id} status ${status} ho gaya`)}catch{setPlots(x=>x.map(p=>p.id===plot.id?{...p,status:previous}:p));if(selected?.id===plot.id)setSelected({...updated,status:previous});show("Status save nahi hua")}finally{setStatusBusy("")}}
 async function savePlot(){if(!selected)return;setBusy(true);try{const r=await fetch("/api/data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"plot",plot:selected})});if(!r.ok)throw new Error();setPlots(x=>x.map(p=>p.id===selected.id?selected:p));show("Plot details save ho gayi")}catch{show("Save nahi hua, dobara try karein")}finally{setBusy(false)}}
 async function saveSettings(){setBusy(true);try{const r=await fetch("/api/data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"settings",settings})});if(!r.ok)throw new Error();show("Project details save ho gayi")}catch{show("Save nahi hua, dobara try karein")}finally{setBusy(false)}}
 function chooseImages(e:React.ChangeEvent<HTMLInputElement>){const chosen=Array.from(e.target.files||[]),allowed=["image/jpeg","image/png","image/webp"],slots=10-gallery.length;if(!chosen.length)return;if(slots<=0){e.target.value="";show("Gallery me pehle se 10 images hain");return}const valid=chosen.filter(file=>allowed.includes(file.type)&&file.size<=8*1024*1024).slice(0,slots);if(valid.length!==chosen.length)show(chosen.length>slots?`Sirf ${slots} aur image upload ho sakti hain`:"Kuch files invalid ya 8 MB se badi hain");uploadPreviews.forEach(URL.revokeObjectURL);setUploadFiles(valid);setUploadPreviews(valid.map(URL.createObjectURL));setUploadProgress(null);e.target.value=""}
 function removeSelected(index:number){URL.revokeObjectURL(uploadPreviews[index]);setUploadFiles(x=>x.filter((_,i)=>i!==index));setUploadPreviews(x=>x.filter((_,i)=>i!==index))}
 async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!uploadFiles.length){show("Pehle image choose karein");return}const form=e.currentTarget,caption=String(new FormData(form).get("caption")||""),total=uploadFiles.length;setBusy(true);setUploadProgress(0);const uploaded:Gallery[]=[];for(let index=0;index<total;index++){setUploadCurrent(index+1);const data=new FormData();data.append("file",uploadFiles[index]);data.append("caption",caption);try{const item=await new Promise<Gallery>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open("POST","/api/gallery");xhr.upload.onprogress=event=>{if(event.lengthComputable)setUploadProgress(Math.round(((index+event.loaded/event.total)/total)*100))};xhr.onerror=()=>reject(new Error("Network error — upload dobara try karein"));xhr.onload=()=>{let j:{item?:Gallery;error?:string}={};try{j=JSON.parse(xhr.responseText)}catch{}if(xhr.status>=200&&xhr.status<300&&j.item)resolve(j.item);else reject(new Error(j.error||`Upload failed (${xhr.status||"network"})`))};xhr.send(data)});uploaded.push(item);setGallery(x=>[item,...x])}catch(error){uploadPreviews.slice(0,index).forEach(URL.revokeObjectURL);setUploadFiles(uploadFiles.slice(index));setUploadPreviews(uploadPreviews.slice(index));setBusy(false);setUploadProgress(null);setUploadCurrent(0);show(`${uploaded.length?`${uploaded.length} upload hui · `:""}${error instanceof Error?error.message:"Upload failed"}`);return}}setBusy(false);setUploadProgress(100);form.reset();uploadPreviews.forEach(URL.revokeObjectURL);setUploadFiles([]);setUploadPreviews([]);setUploadCurrent(0);setTimeout(()=>setUploadProgress(null),1000);show(`${uploaded.length} image${uploaded.length>1?"s":""} gallery me upload ho gayi`)}
 async function remove(id:string){if(!confirm("Is image ko gallery se delete karein?"))return;setDeleteBusy(id);try{const r=await fetch(`/api/gallery?id=${id}`,{method:"DELETE"});if(!r.ok)throw new Error();setGallery(x=>x.filter(i=>i.id!==id));show("Image delete ho gayi")}catch{show("Image delete nahi hui. Dobara try karein.")}finally{setDeleteBusy("")}}
 const navItems=user.role==="super_admin"?[...baseNavItems,["users",Users,"Client Admins"] as const]:baseNavItems;
 const projectLogoUrl=settings.logoName?`/api/project-asset/logo?projectId=${encodeURIComponent(projectId)}&v=${encodeURIComponent(settings.logoVersion||settings.logoName)}`:"";
 return <div className="admin-shell" style={{"--project-accent":settings.accentColor} as React.CSSProperties}><aside className="side"><div className="logo">{projectLogoUrl?<img className="client-project-logo" src={projectLogoUrl} alt={`${settings.brandName} logo`} width={46} height={46}/>:<span>{settings.brandShort.slice(0,4)}</span>}<div><b>{settings.brandName}</b><small>{user.role==="super_admin"?"SUPER ADMIN":"CLIENT ADMIN"}</small></div></div><nav>{navItems.map(([id,Icon,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon size={19}/>{label}</button>)}</nav><div className="account"><div className="avatar">{user.name[0]?.toUpperCase()}</div><div><b>{user.name}</b><small>{user.email}</small></div><a href={signOut}>Sign out</a></div></aside>
 <main className="content"><header><div><p>{settings.projectName.toUpperCase()} · {user.role==="super_admin"?"SUPER ADMIN":"CLIENT ADMIN"}</p><h1>{tab==="overview"?"Dashboard":tab==="mapper"?"Plot Mapper Engine":tab==="plots"?"Plot Management":tab==="gallery"?"Gallery Manager":tab==="users"?"Client Access":"Project Settings"}</h1></div><a className="site-link" href={isTiyansh?"/":`/preview/${encodeURIComponent(projectId)}`} target="_blank" rel="noopener noreferrer"><ExternalLink size={17}/> View Site</a></header>
 {tab==="overview"&&<><section className="stats"><Stat label="Total Plots" value={plots.length} color="blue"/><Stat label="Available" value={counts.available} color="green"/><Stat label="Booked" value={counts.booked} color="amber"/><Stat label="Sold" value={counts.sold} color="red"/></section><section className="overview-grid"><div className="card master-card"><div className="card-title"><div><h2>Project masterplan</h2><p>Live inventory ka visual reference</p></div></div><img src={isTiyansh?"/project/masterplan.jpg":"/api/project-asset/masterplan"} alt={`${settings.projectName} masterplan`} loading="eager" decoding="async"/></div><div className="card quick"><h2>Quick actions</h2><button onClick={()=>setTab("plots")}><MapIcon/>Plot status update karein</button><button onClick={()=>setTab("gallery")}><Upload/>Gallery image upload karein</button><button onClick={()=>setTab("settings")}><Phone/>Contact details edit karein</button></div></section></>}
 {tab==="plots"&&<section className="plots-layout"><div className="card plot-list"><div className="plot-list-head"><div><h2>All Plots</h2><p>{plots.length} plots · status dropdown se direct save hoga</p></div></div><div className="plot-rows">{plots.map(p=><div key={p.id} className={selected?.id===p.id?"plot-row selected":"plot-row"}><button onClick={()=>setSelected({...p})}><b>{p.id}</b><span>{p.sqft.toLocaleString()} sq.ft</span></button><select className={`status-select ${p.status}`} aria-label={`${p.id} status`} value={p.status} disabled={statusBusy===p.id} onChange={e=>changeStatus(p,e.target.value)}><option value="available">Available</option><option value="booked">Booked</option><option value="sold">Sold</option></select></div>)}</div></div>{selected&&<div className="card editor"><div className="editor-head"><div><p>EDITING PLOT</p><h2>{selected.id}</h2></div><span className={`big-status ${selected.status}`}>{selected.status}</span></div><div className="form-grid"><Field label="Square feet"><input type="number" value={selected.sqft} onChange={e=>setSelected({...selected,sqft:+e.target.value})}/></Field><Field label="Square meters"><input type="number" value={selected.sqm} onChange={e=>setSelected({...selected,sqm:+e.target.value})}/></Field><Field label="Square yards"><input type="number" value={selected.sqyd} onChange={e=>setSelected({...selected,sqyd:+e.target.value})}/></Field><Field label="Dimensions"><input value={selected.dimensions} onChange={e=>setSelected({...selected,dimensions:e.target.value})}/></Field><Field label="Road access"><input value={selected.road} onChange={e=>setSelected({...selected,road:e.target.value})}/></Field><Field label="Status"><select value={selected.status} onChange={e=>setSelected({...selected,status:e.target.value})}><option value="available">Available</option><option value="booked">Booked</option><option value="sold">Sold</option></select></Field><Field label="Internal notes" wide><textarea rows={4} value={selected.notes||""} onChange={e=>setSelected({...selected,notes:e.target.value})}/></Field></div><button className="primary" disabled={busy} onClick={savePlot}><Save size={18}/>{busy?"Saving…":"Save Plot Details"}</button></div>}</section>}
 {tab==="gallery"&&<section className="card gallery-card"><form onSubmit={upload} className="upload-box multi-upload"><div className="upload-intro"><Upload size={28}/><div><h2>Gallery me images add karein</h2><p>{gallery.length}/10 uploaded · JPG, PNG ya WebP · har image maximum 8 MB</p></div></div><label className="image-picker"><ImagePlus size={30}/><span>{uploadFiles.length?"Selection change karein":"Images choose karein"}</span><input name="file" type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={busy||gallery.length>=10} onChange={chooseImages}/></label><div className="upload-details"><b>{uploadFiles.length?`${uploadFiles.length} image selected`:gallery.length>=10?"Gallery full hai":"No image selected"}</b><small>{uploadFiles.length?`${uploadFiles.reduce((sum,file)=>sum+file.size,0)/1024/1024<1?"Less than 1":(uploadFiles.reduce((sum,file)=>sum+file.size,0)/1024/1024).toFixed(2)} MB total · Ready to upload`:gallery.length>=10?"Nayi image ke liye ek purani image delete karein":"Ek baar me multiple images select kar sakte hain"}</small><input name="caption" placeholder="Common caption (optional)" disabled={busy}/></div><button className="primary upload-action" disabled={busy||!uploadFiles.length}>{busy?`Uploading ${uploadCurrent}/${uploadFiles.length}`:`Upload ${uploadFiles.length||""} Image${uploadFiles.length===1?"":"s"}`}</button>{uploadFiles.length>0&&<div className="selected-images">{uploadPreviews.map((src,index)=><article key={src}><img src={src} alt={`Selected image ${index+1}`} decoding="async"/><button type="button" aria-label={`Remove ${uploadFiles[index].name}`} disabled={busy} onClick={()=>removeSelected(index)}>×</button><small>{uploadFiles[index].name}</small></article>)}</div>}{uploadProgress!==null&&<div className="upload-progress" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={uploadProgress}><span style={{width:`${uploadProgress}%`}}></span><small>{uploadProgress<100?`${uploadProgress}% uploaded`:"Upload complete"}</small></div>}</form><div className="gallery-list-head"><div><h2>Uploaded images</h2><p>Admin gallery me saved images</p></div><b>{gallery.length}/10</b></div><div className="admin-gallery-list">{gallery.length?gallery.map(item=><article key={item.id}><img src={`/api/gallery/${item.id}`} alt={item.caption||item.filename} loading="lazy" decoding="async"/><div><b>{item.caption||item.filename}</b><small>{item.filename}</small></div><button type="button" disabled={deleteBusy===item.id} onClick={()=>remove(item.id)}><Trash2 size={17}/>{deleteBusy===item.id?"Deleting…":"Delete"}</button></article>):<div className="empty">Abhi gallery me koi image nahi hai.</div>}</div></section>}
 {tab==="settings"&&<section className="card settings-card"><div className="section-title"><Building2/><div><h2>Brand, template & contact details</h2><p>Client website और admin panel पर दिखने वाली information</p></div></div><div className="form-grid settings-form">{(Object.entries(settings) as [keyof typeof tiyanshDefaults,string][]).map(([k,v])=><Field key={k} label={settingLabels[k]} wide={k==="address"}>{k==="template"?<select value={v} onChange={e=>setSettings({...settings,template:e.target.value})}><option value="plots">Real-estate plots</option><option value="business">Business showcase</option></select>:k==="accentColor"?<input type="color" value={v} onChange={e=>setSettings({...settings,accentColor:e.target.value})}/>:<input value={v} maxLength={k==="brandShort"?4:undefined} onChange={e=>setSettings({...settings,[k]:e.target.value})}/>}</Field>)}</div><button className="primary" disabled={busy} onClick={saveSettings}><Save size={18}/>Save Changes</button></section>}
 {tab==="users"&&user.role==="super_admin"&&<ClientAdminManager notify={show}/>}
 </main>{toast&&<div className="toast-admin">{toast}</div>}</div>
}
function Stat({label,value,color}:{label:string;value:number;color:string}){return <div className={`stat ${color}`}><small>{label}</small><b>{value}</b><span></span></div>}
function Field({label,wide,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={wide?"wide":""}><span>{label}</span>{children}</label>}
