"use client";
import { useCallback,useEffect,useState } from "react";
import { Copy,KeyRound,ShieldCheck,Trash2,UserCheck,UserPlus,UserX } from "lucide-react";

type ClientAdmin={id:string;email:string;name:string;role:string;status:"active"|"disabled";mustChangePassword:boolean;createdAt:string;lastLoginAt:string|null};
const makePassword=()=>{
  const chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%";
  const values=crypto.getRandomValues(new Uint32Array(18));
  return Array.from(values,value=>chars[value%chars.length]).join("");
};

export default function ClientAdminManager({notify}:{notify:(message:string)=>void}){
  const [users,setUsers]=useState<ClientAdmin[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[name,setName]=useState(""),[email,setEmail]=useState(""),[credential,setCredential]=useState<{name:string;email:string;password:string}|null>(null);
  const load=useCallback(async()=>{setLoading(true);try{const response=await fetch("/api/admin/users",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error);setUsers(data.users||[])}catch(error){notify(error instanceof Error?error.message:"Client admins load nahi hue")}finally{setLoading(false)}},[notify]);
  useEffect(()=>{load()},[load]);
  async function create(event:React.FormEvent){event.preventDefault();if(busy)return;const password=makePassword();setBusy("create");try{const response=await fetch("/api/admin/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,email,password})});const data=await response.json();if(!response.ok)throw new Error(data.error);setUsers(current=>[data.user,...current]);setCredential({name,email:email.trim().toLowerCase(),password});setName("");setEmail("");notify("Client admin access ready hai")}catch(error){notify(error instanceof Error?error.message:"Account create nahi hua")}finally{setBusy("")}}
  async function reset(user:ClientAdmin){if(!confirm(`${user.email} ka password reset karein?`))return;const password=makePassword();setBusy(user.id);try{const response=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:user.id,action:"reset_password",password})});const data=await response.json();if(!response.ok)throw new Error(data.error);setCredential({name:user.name,email:user.email,password});notify("Naya temporary password ready hai")}catch(error){notify(error instanceof Error?error.message:"Password reset nahi hua")}finally{setBusy("")}}
  async function toggle(user:ClientAdmin){setBusy(user.id);try{const response=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:user.id,action:"toggle"})});const data=await response.json();if(!response.ok)throw new Error(data.error);setUsers(current=>current.map(item=>item.id===user.id?{...item,status:data.status}:item));notify(data.status==="active"?"Client access active hai":"Client access disabled hai")}catch(error){notify(error instanceof Error?error.message:"Access update nahi hua")}finally{setBusy("")}}
  async function remove(user:ClientAdmin){if(!confirm(`${user.email} ka access permanently delete karein?`))return;setBusy(user.id);try{const response=await fetch(`/api/admin/users?id=${encodeURIComponent(user.id)}`,{method:"DELETE"});const data=await response.json();if(!response.ok)throw new Error(data.error);setUsers(current=>current.filter(item=>item.id!==user.id));notify("Client admin delete ho gaya")}catch(error){notify(error instanceof Error?error.message:"Account delete nahi hua")}finally{setBusy("")}}
  async function copyCredential(){if(!credential)return;await navigator.clipboard.writeText(`Admin URL: ${location.origin}/admin/login\nEmail: ${credential.email}\nTemporary password: ${credential.password}`);notify("Login details copy ho gayi")}
  return <section className="client-admins">
    <div className="card client-create-card"><div className="section-title"><UserPlus/><div><h2>Create client access</h2><p>Client ka email dijiye; secure temporary password automatic banega.</p></div></div><form className="client-create-form" onSubmit={create}><label><span>Client name</span><input required minLength={2} maxLength={80} value={name} onChange={event=>setName(event.target.value)} placeholder="Client or company name"/></label><label><span>Client email</span><input required type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="client@example.com"/></label><button className="primary" disabled={busy==="create"}>{busy==="create"?"Creating…":"Create Client Access"}</button></form></div>
    {credential&&<div className="credential-card" role="status"><div><ShieldCheck/><span><b>Login details ready</b><small>Password केवल अभी दिखाई जा रहा है। Client को सुरक्षित तरीके से भेजें।</small></span></div><dl><div><dt>Admin URL</dt><dd>{location.origin}/admin/login</dd></div><div><dt>Email</dt><dd>{credential.email}</dd></div><div><dt>Temporary password</dt><dd>{credential.password}</dd></div></dl><button onClick={copyCredential}><Copy/> Copy login details</button><button className="credential-close" aria-label="Hide login details" onClick={()=>setCredential(null)}>×</button></div>}
    <div className="card client-list-card"><div className="client-list-head"><div><h2>Client admins</h2><p>Super Admin se sabhi client accounts control karein.</p></div><b>{users.length}</b></div>{loading?<div className="empty">Client admins load ho rahe hain…</div>:users.length?<div className="client-admin-list">{users.map(user=><article key={user.id}><div className={`client-avatar ${user.status}`}>{user.name[0]?.toUpperCase()}</div><div className="client-identity"><b>{user.name}</b><span>{user.email}</span><small>Last login: {user.lastLoginAt?new Date(user.lastLoginAt).toLocaleString():"Never"}</small></div><em className={user.status}>{user.status}</em><div className="client-actions"><button disabled={busy===user.id} onClick={()=>reset(user)}><KeyRound/>Reset password</button><button disabled={busy===user.id} onClick={()=>toggle(user)}>{user.status==="active"?<><UserX/>Disable</>:<><UserCheck/>Enable</>}</button><button className="danger" disabled={busy===user.id} onClick={()=>remove(user)}><Trash2/>Delete</button></div></article>)}</div>:<div className="empty">Abhi koi client admin nahi hai.</div>}</div>
  </section>
}
