"use client";
import { useEffect,useState } from "react";
import { Copy,Globe2,KeyRound,ShieldCheck,Trash2,UserCheck,UserPlus,UserX } from "lucide-react";
import { generateTemporaryClientPassword } from "./client-password-policy";
type ClientAdmin={id:string;email:string;name:string;role:string;status:"active"|"disabled";mustChangePassword:boolean;createdAt:string;lastLoginAt:string|null;projectId:string;projectName:string;projectSlug?:string;publicHost:string|null;adminHost:string|null;adminUrl?:string};
type Project={id:string;name:string;status:string;adminCount:number;publicHost:string|null;adminHost:string|null};
type Audit={action:string;actorEmail:string;projectId:string|null;targetId:string|null;createdAt:string};
export default function ClientAdminManager({notify}:{notify:(message:string)=>void}){
 const [users,setUsers]=useState<ClientAdmin[]>([]),[projects,setProjects]=useState<Project[]>([]),[audits,setAudits]=useState<Audit[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[name,setName]=useState(""),[email,setEmail]=useState(""),[projectName,setProjectName]=useState(""),[existingProjectId,setExistingProjectId]=useState(""),[publicHost,setPublicHost]=useState(""),[adminHost,setAdminHost]=useState(""),[fallbackAdminUrl,setFallbackAdminUrl]=useState(""),[credential,setCredential]=useState<{name:string;email:string;password:string;adminUrl:string}|null>(null);
 useEffect(()=>{let active=true;fetch("/api/admin/users",{cache:"no-store"}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);if(active){setUsers(data.users||[]);setProjects(data.projects||[]);setAudits(data.audits||[]);setFallbackAdminUrl(data.clientAdminUrl||"")}}).catch(error=>{if(active)notify(error instanceof Error?error.message:"Client admins load nahi hue")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[notify]);
 useEffect(()=>{if(!credential)return;const timer=setTimeout(()=>setCredential(null),5*60*1000);return()=>clearTimeout(timer)},[credential]);
 async function create(event:React.FormEvent){event.preventDefault();if(busy)return;const password=generateTemporaryClientPassword();setBusy("create");try{const response=await fetch("/api/admin/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,email,password,projectId:existingProjectId||undefined,projectName,publicHost,adminHost})}),data=await response.json();if(!response.ok)throw new Error(data.error);setUsers(current=>[data.user,...current]);setProjects(current=>current.map(project=>project.id===data.user.projectId?{...project,adminCount:Number(project.adminCount)+1}:project));const adminUrl=data.user.adminUrl||data.clientAdminUrl||fallbackAdminUrl;setCredential({name,email:email.trim().toLowerCase(),password,adminUrl});setName("");setEmail("");setProjectName("");setExistingProjectId("");setPublicHost("");setAdminHost("");notify("Client project aur admin access ready hai")}catch(error){notify(error instanceof Error?error.message:"Account create nahi hua")}finally{setBusy("")}}
 async function reset(user:ClientAdmin){if(!confirm(`${user.email} ka password reset karein? Iske current sessions logout ho jayenge.`))return;const password=generateTemporaryClientPassword();setBusy(user.id);try{const response=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:user.id,action:"reset_password",password})}),data=await response.json();if(!response.ok)throw new Error(data.error);setCredential({name:user.name,email:user.email,password,adminUrl:user.adminUrl||fallbackAdminUrl});notify("Naya temporary password ready hai")}catch(error){notify(error instanceof Error?error.message:"Password reset nahi hua")}finally{setBusy("")}}
 async function toggle(user:ClientAdmin){setBusy(user.id);try{const response=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:user.id,action:"toggle"})}),data=await response.json();if(!response.ok)throw new Error(data.error);setUsers(current=>current.map(item=>item.id===user.id?{...item,status:data.status}:item));notify(data.status==="active"?"Client access active hai":"Client access disabled aur sessions revoked hain")}catch(error){notify(error instanceof Error?error.message:"Access update nahi hua")}finally{setBusy("")}}
 async function domains(user:ClientAdmin){const website=prompt("Website domain — example: tiyansh.com",user.publicHost||"");if(website===null)return;const admin=prompt("Admin domain — example: admin.tiyansh.com",user.adminHost||"");if(admin===null)return;setBusy(user.id);try{const response=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:user.id,action:"domains",publicHost:website,adminHost:admin})}),data=await response.json();if(!response.ok)throw new Error(data.error);setUsers(current=>current.map(item=>item.id===user.id?{...item,publicHost:data.publicHost,adminHost:data.adminHost}:item));notify("Domains mapped hain; Cloudflare custom domains अलग से attach करें")}catch(error){notify(error instanceof Error?error.message:"Domains save nahi hue")}finally{setBusy("")}}
 async function remove(user:ClientAdmin){const sameProject=users.filter(item=>item.projectId===user.projectId).length,message=sameProject>1?`${user.name} का admin access हटाएँ? Project और बाकी admins सुरक्षित रहेंगे।`:`${user.projectName} का आखिरी admin हटाने पर project data और gallery permanently delete होंगे।`;if(!confirm(message))return;setBusy(user.id);try{const response=await fetch(`/api/admin/users?id=${encodeURIComponent(user.id)}`,{method:"DELETE"}),data=await response.json();if(!response.ok)throw new Error(data.error);setUsers(current=>current.filter(item=>item.id!==user.id));setProjects(current=>data.projectDeleted?current.filter(item=>item.id!==user.projectId):current.map(item=>item.id===user.projectId?{...item,adminCount:Math.max(0,Number(item.adminCount)-1)}:item));notify(data.projectDeleted?"Client project data delete हो गया":"Staff admin access हटा दिया गया")}catch(error){notify(error instanceof Error?error.message:"Account delete nahi hua")}finally{setBusy("")}}
 async function copyCredential(){if(!credential)return;await navigator.clipboard.writeText(`Admin URL: ${credential.adminUrl}\nEmail: ${credential.email}\nTemporary password: ${credential.password}`);notify("Login details copy ho gayi")}
 return <section className="client-admins"><div className="card client-create-card"><div className="section-title"><UserPlus/><div><h2>Create client access</h2><p>Existing project में staff admin जोड़ें या नया client project बनाइए।</p></div></div><form className="client-create-form" onSubmit={create}><label><span>Existing project (optional)</span><select value={existingProjectId} onChange={event=>setExistingProjectId(event.target.value)}><option value="">Create a new project</option>{projects.map(project=><option key={project.id} value={project.id}>{project.name} · {project.adminCount} admin</option>)}</select></label>{!existingProjectId&&<label><span>New project name</span><input required minLength={2} maxLength={100} value={projectName} onChange={event=>setProjectName(event.target.value)} placeholder="Client project name"/></label>}<label><span>Client name</span><input required minLength={2} maxLength={80} value={name} onChange={event=>setName(event.target.value)} placeholder="Client or staff name"/></label><label><span>Client email</span><input required type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="client@example.com"/></label><label><span>Website domain (optional)</span><input value={publicHost} onChange={event=>setPublicHost(event.target.value)} placeholder="client.com"/></label><label><span>Admin domain (optional)</span><input value={adminHost} onChange={event=>setAdminHost(event.target.value)} placeholder="admin.client.com"/></label><button className="primary" disabled={busy==="create"}>{busy==="create"?"Creating…":"Create Client Access"}</button></form></div>
 {credential&&<div className="credential-card" role="status"><div><ShieldCheck/><span><b>Login details ready</b><small>Password केवल अभी दिखाई जा रहा है। First login पर client नया password बनाएगा।</small></span></div><dl><div><dt>Admin URL</dt><dd>{credential.adminUrl}</dd></div><div><dt>Email</dt><dd>{credential.email}</dd></div><div><dt>Temporary password</dt><dd>{credential.password}</dd></div></dl><button onClick={copyCredential}><Copy/> Copy login details</button><button className="credential-close" aria-label="Hide login details" onClick={()=>setCredential(null)}>×</button></div>}
 <div className="card client-list-card"><div className="client-list-head"><div><h2>Client projects & admins</h2><p>हर project, domain और staff access Super Admin से control करें।</p></div><b>{users.length}</b></div>{loading?<div className="empty">Client projects load ho rahe hain…</div>:users.length?<div className="client-admin-list">{users.map(user=><article key={user.id}><div className={`client-avatar ${user.status}`}>{user.projectName[0]?.toUpperCase()}</div><div className="client-identity"><b>{user.projectName}</b><span>{user.name} · {user.email}</span><small>Website: {user.publicHost||"pending"} · Admin: {user.adminHost||"pending"}</small><small>{user.mustChangePassword?"Temporary password change pending":"Password activated"} · Last login: {user.lastLoginAt?new Date(user.lastLoginAt).toLocaleString():"Never"}</small></div><em className={user.status}>{user.status}</em><div className="client-actions"><button disabled={busy===user.id} onClick={()=>domains(user)}><Globe2/>Domains</button><button disabled={busy===user.id} onClick={()=>reset(user)}><KeyRound/>Reset password</button><button disabled={busy===user.id} onClick={()=>toggle(user)}>{user.status==="active"?<><UserX/>Disable</>:<><UserCheck/>Enable</>}</button><button className="danger" disabled={busy===user.id} onClick={()=>remove(user)}><Trash2/>Remove</button></div></article>)}</div>:<div className="empty">Abhi koi client access nahi hai। ऊपर से पहला project और access बनाइए।</div>}</div>
 <div className="card audit-card"><div className="client-list-head"><div><h2>Security activity</h2><p>Latest 50 owner और client actions</p></div><b>{audits.length}</b></div><div className="audit-list">{audits.length?audits.map((item,index)=><article key={`${item.createdAt}-${index}`}><b>{item.action.replaceAll("."," · ")}</b><span>{item.actorEmail}</span><time>{new Date(item.createdAt).toLocaleString()}</time></article>):<div className="empty">Abhi कोई activity नहीं है।</div>}</div></div></section>
}
