"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {FileText,ImagePlus,MousePointer2,Save,Trash2,Undo2} from "lucide-react";

type Point=[number,number];
type Plot={id:string;sqft:number;sqm:number;sqyd:number;dimensions:string;road:string;status:string;notes?:string;featured?:boolean;polygon?:string};

export default function PlotMapper({notify,projectId}:{notify:(message:string)=>void;projectId:string}){
 const assetUrl=(kind:string)=>`/api/project-asset/${kind}?projectId=${encodeURIComponent(projectId)}`;
 const [plots,setPlots]=useState<Plot[]>([]),[points,setPoints]=useState<Point[]>([]),[mode,setMode]=useState<"rectangle"|"polygon">("rectangle"),[plotId,setPlotId]=useState(""),[dimensions,setDimensions]=useState(""),[sqft,setSqft]=useState(""),[road,setRoad]=useState(""),[imageUrl,setImageUrl]=useState(()=>assetUrl("masterplan")),[imageReady,setImageReady]=useState(false),[busy,setBusy]=useState(false),[pdfName,setPdfName]=useState("");
 const imageRef=useRef<HTMLImageElement|null>(null);
 // projectId is also the component key, so switching projects remounts this editor.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{fetch(`/api/super-mapper?projectId=${encodeURIComponent(projectId)}`,{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(data=>{setPlots((data.plots||[]).filter((p:Plot)=>p.polygon));setPdfName(data.settings?.sourcePdfName||"")}).catch(()=>notify("Project mapper data load नहीं हुआ"))},[projectId]);
 const draft=useMemo(()=>mode==="rectangle"&&points.length===2?[[points[0][0],points[0][1]],[points[1][0],points[0][1]],points[1],[points[0][0],points[1][1]]] as Point[]:points,[mode,points]);
 function point(event:React.PointerEvent<SVGSVGElement>){const box=event.currentTarget.getBoundingClientRect(),p:[number,number]=[(event.clientX-box.left)/box.width,(event.clientY-box.top)/box.height];if(mode==="rectangle"){setPoints(current=>current.length>=2?[p]:[...current,p])}else setPoints(current=>current.length<80?[...current,p]:current)}
 async function upload(file:File,kind:"masterplan"|"sourcePdf"){const data=new FormData();data.append("projectId",projectId);data.append("kind",kind);data.append("file",file);setBusy(true);try{const r=await fetch("/api/super-mapper",{method:"POST",body:data}),j=await r.json();if(!r.ok)throw new Error(j.error);if(kind==="masterplan"){setImageReady(false);setImageUrl(j.url)}else setPdfName(file.name);notify(kind==="masterplan"?"Masterplan तैयार है":"Technical PDF reference save हो गया")}catch(error){notify(error instanceof Error?error.message:"Upload नहीं हुआ")}finally{setBusy(false)}}
 async function save(){const id=plotId.trim().toUpperCase();if(!id||draft.length<3){notify("Plot number और पूरी boundary जरूरी है");return}const area=Number(sqft)||0,plot:Plot={id,sqft:area,sqm:area/10.7639,sqyd:area/9,dimensions:dimensions.trim(),road:road.trim(),status:"available",polygon:JSON.stringify(draft)};setBusy(true);try{const r=await fetch("/api/super-mapper",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId,plot})}),j=await r.json();if(!r.ok)throw new Error(j.error);setPlots(current=>[...current.filter(p=>p.id!==id),j.plot]);setPoints([]);setPlotId("");setDimensions("");setSqft("");setRoad("");notify(`Plot ${id} clickable बन गया`)}catch(error){notify(error instanceof Error?error.message:"Plot save नहीं हुआ")}finally{setBusy(false)}}
 async function remove(plot:Plot){if(!confirm(`Plot ${plot.id} की clickable boundary हटाएँ?`))return;const cleared={...plot,polygon:""};setBusy(true);try{const r=await fetch("/api/super-mapper",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId,plot:cleared})});if(!r.ok)throw new Error();setPlots(current=>current.filter(p=>p.id!==plot.id));notify("Boundary हटा दी गई")}catch{notify("Boundary नहीं हटी")}finally{setBusy(false)}}
 return <section className="mapper-shell"><div className="card mapper-tools"><div className="section-title"><MousePointer2/><div><h2>Plot Mapper Engine</h2><p>Masterplan पर tap करके clickable plots बनाइए</p></div></div><div className="mapper-upload-row"><label className="mapper-upload"><ImagePlus/>3D masterplan<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],"masterplan")}/></label><label className="mapper-upload"><FileText/>Technical PDF<input type="file" accept="application/pdf" disabled={busy} onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],"sourcePdf")}/></label>{pdfName&&<a href="/api/project-asset/sourcePdf" target="_blank" rel="noreferrer">Open {pdfName}</a>}</div><div className="mapper-mode"><button className={mode==="rectangle"?"active":""} onClick={()=>{setMode("rectangle");setPoints([])}}>Rectangle: 2 taps</button><button className={mode==="polygon"?"active":""} onClick={()=>{setMode("polygon");setPoints([])}}>Polygon: corner taps</button></div><div className="mapper-fields"><input value={plotId} onChange={e=>setPlotId(e.target.value)} placeholder="Plot no. A-01"/><input value={dimensions} onChange={e=>setDimensions(e.target.value)} placeholder="Dimensions 40×85"/><input type="number" value={sqft} onChange={e=>setSqft(e.target.value)} placeholder="Area sq.ft"/><input value={road} onChange={e=>setRoad(e.target.value)} placeholder="Road access"/></div><div className="mapper-actions"><button disabled={!points.length} onClick={()=>setPoints(current=>current.slice(0,-1))}><Undo2/>Undo point</button><button disabled={!points.length} onClick={()=>setPoints([])}>Clear</button><button className="primary" disabled={busy||draft.length<3} onClick={save}><Save/>Save clickable plot</button></div><small className="mapper-help">Rectangle mode: plot के ऊपर-left और नीचे-right corner पर tap करें। Irregular plot के लिए Polygon mode चुनें और सभी corners tap करें।</small></div>
 <div className="mapper-work"><div className="mapper-canvas card">{!imageReady&&<div className="mapper-loading">Masterplan upload करें या image load होने दें…</div>}<div className="mapper-image-wrap"><img ref={imageRef} src={imageUrl} alt="Project masterplan" onLoad={()=>setImageReady(true)} onError={()=>setImageReady(false)}/>{imageReady&&<svg viewBox="0 0 1000 1000" preserveAspectRatio="none" onPointerDown={point}>{plots.map(plot=>{const p=JSON.parse(plot.polygon||"[]") as Point[];return <polygon key={plot.id} points={p.map(([x,y])=>`${x*1000},${y*1000}`).join(" ")}><title>{plot.id}</title></polygon>})}{draft.length>0&&<polygon className="draft" points={draft.map(([x,y])=>`${x*1000},${y*1000}`).join(" ")}/>} {points.map(([x,y],i)=><circle className="point" key={i} cx={x*1000} cy={y*1000} r="8"/>)}</svg>}</div></div><aside className="card mapper-list"><h3>Mapped plots <b>{plots.length}</b></h3>{plots.length?plots.sort((a,b)=>a.id.localeCompare(b.id,undefined,{numeric:true})).map(plot=><article key={plot.id}><span><b>{plot.id}</b><small>{plot.dimensions||`${plot.sqft} sq.ft`}</small></span><button onClick={()=>remove(plot)} aria-label={`Remove ${plot.id}`}><Trash2/></button></article>):<p>अभी कोई clickable plot नहीं है।</p>}</aside></div></section>
}
