"use client";
import { useState } from "react";
import { Eye,EyeOff,KeyRound } from "lucide-react";

export default function ChangePasswordForm({email}:{email:string}){
  const [password,setPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState(""),[showPassword,setShowPassword]=useState(false),[showConfirm,setShowConfirm]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/admin/change-password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password,confirmPassword})});const data=await response.json();if(!response.ok)throw new Error(data.error);location.replace("/admin")}catch(value){setError(value instanceof Error?value.message:"Password change nahi hua")}finally{setBusy(false)}}
  return <main className="login-page"><section className="login-card"><div className="login-icon"><KeyRound/></div><h1>Create New Password</h1><p>{email}<br/>Temporary password ko change karna zaroori hai.</p><form onSubmit={submit}><label><span>NEW PASSWORD</span><div className="login-input"><input type={showPassword?"text":"password"} required minLength={12} maxLength={128} autoComplete="new-password" value={password} onChange={event=>setPassword(event.target.value)} placeholder="12+ characters"/><button type="button" onClick={()=>setShowPassword(value=>!value)} aria-label={showPassword?"Hide new password":"Show new password"}>{showPassword?<EyeOff/>:<Eye/>}</button></div></label><label><span>CONFIRM PASSWORD</span><div className="login-input"><input type={showConfirm?"text":"password"} required minLength={12} maxLength={128} autoComplete="new-password" value={confirmPassword} onChange={event=>setConfirmPassword(event.target.value)} placeholder="Password dobara likhein"/><button type="button" onClick={()=>setShowConfirm(value=>!value)} aria-label={showConfirm?"Hide confirmed password":"Show confirmed password"}>{showConfirm?<EyeOff/>:<Eye/>}</button></div></label><small>Uppercase, lowercase, number aur special character use karein.</small>{error&&<div className="login-error">{error}</div>}<button className="login-submit" disabled={busy}>{busy?"Saving…":"Save New Password"}</button></form></section></main>
}
